# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mechasparrow
email: mechasparrow@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The official website of Mechasparrow. A mechanical bird that builds stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mechasparrow.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: mechasparrow
github_username:  mechasparrow
medium_username: mechasparrow
youtube_channel: https://www.youtube.com/channel/UChhfBPfgwfu69N4o-MWZK9A?view_as=subscriber

# Build settings
markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-crosspost-to-medium

search: true
paginate: 3
paginate_path: /page:num/

disqus:
  shortname: mechasparrow

google_analytics: UA-119139998-1

collections:
  games:
    output: true
    permalink: /games/:path/

jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: draft

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
